# config
server:
  port: 9000

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: false
    api-docs:
      path: /api-docs
    show-actuator: false
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    group-configs:
      0:
        group: all
        paths-to-match: /**

mybatis:
  mapper-locations:
    classpath:mapper/**/*.xml
  type-aliases-package: com.main.model
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar


info:
  properties:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/wb
      username: root
      password: Abcd123@